wasmfx/wasmfxtime

Cargo.lock
Cargo.toml
cranelift/filetests/src/test_wasm/env.rs
cranelift/wasm/src/environ/dummy.rs
cranelift/wasm/src/environ/spec.rs
cranelift/wasm/src/sections_translator.rs
crates/environ/src/module_environ.rs
crates/types/src/lib.rs

This patch uses release `wasmfx-tools-1.0.42.rev+1`.

Use hotfixed wasmfx-tools

---

crates/runtime/src/continuation.rs

This patch fixes an unused variable warning triggered in `continuation.rs` when compiling in release mode.
```
warning: unused variable: `running_contobj`
--> crates/runtime/src/continuation.rs:374:13
|
374 |         let running_contobj = instance.typed_continuations_store();
|             ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_running_contobj`
|
= note: `#[warn(unused_variables)]` on by default
```

Silence unused variable warning in release mode.

---

cranelift/filetests/src/test_wasm/env.rs
cranelift/wasm/src/code_translator.rs
cranelift/wasm/src/environ/dummy.rs
cranelift/wasm/src/environ/spec.rs
cranelift/wasm/src/translation_utils.rs
crates/cranelift/src/func_environ.rs

Currently, the translation of `resume` instructions is somewhat arbitrarily split between `translate_operator` in `code_translator.rs` and `func_environ.rs`. The low-level nature of translating `resume` requires a lot of functionality found only in the latter, which required us to add many helper functions to the `FuncEnvironment` trait (i.e., `spec.rs`). As a result, every change to the translation requires a lot of unnecessary busywork (updating `spec.rs`, `dummy.rs` and `env.rs`).
This particularly obstructs my subsequent optimisation work.
This PR consolidates all of the logic for translating `resume` in `func_environ.rs`. The only work left to do inside  `translate_operator` is very minor, specifically the interaction with the stack and interpreting the resume table. The …

Consolidate translation of resume instructions in FuncEnvironment

---

Cargo.lock
crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/runtime/Cargo.toml
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

This PR removes the libcall `cont_obj_has_state_invoked` and replaces it with a direct implementation.
To this end, we derive `IntoPrimitive` and `TryFromPrimitive` for the `State` enum, using the `num_enum` crate (already used elsewhere within wasmtime), to convert between `State` and integers.

Remove libcall cont_obj_has_state_invoked

---

crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

This PR removes the `cont_obj_occupy_next_args_slots` libcall and replaces it with direct IR generation.

Remove cont_obj_occupy_next_args_slots libcall

---

crates/cranelift/src/func_environ.rs

This patch translate `ref.null cont` and `ref.null nocont` to the constant `0` with `pointer_type` given by the compilation environment. I haven't thought this through deeply, but I think they should be treated the same as `func` and typed function references.

Enable compilation of `ref.null` with `cont`/`nocont` heap type.

---

cranelift/wasm/src/code_translator.rs
crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

A `ContinuationObject` contains two fields of type `Payloads`: `args` and `tag_return_values`. The `Payloads` type is basically just a manually managed vector.
We currently access the `args` Payloads object through jitted code, but use libcalls to access the `tag_return_values` object. This PR changes this, removing the libcalls `cont_obj_occupy_next_tag_returns_slots`, `cont_obj_get_tag_return_values_buffer` and `cont_obj_deallocate_tag_return_values_buffer`.
We re-use the existing logic for `args` to access the identically structured `tag_return_values`. The only difference is that the `args` object is allocated when `ContinuationObject`s are created, while `tag_return_values` are allocated and deallocated when needed. As a result, this PR also adds new libcalls for general purpose …

Manipulate tag_return_values using generated code rather than libcalls

---

crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/runtime/src/libcalls.rs

Adds `tc_` to the names of all of our libcalls.

prefix all of our own libcalls with tc_

---

crates/runtime/src/continuation.rs
crates/wast/src/wast.rs
tests/misc_testsuite/typed-continuations/unhandled.wast

This patch provides an implementation for the Wast `assert_suspension` directive, enabling us to run test cases that tests for unhandled suspensions.

Implement `AssertSuspension`

---

crates/runtime/src/traphandlers/backtrace.rs

This patch is a follow up on PR #35. It partially addresses issue presence of stack switching as older frame pointers are not guaranteed to be greater than the current frame pointer (e.g. tracing across stack boundaries).

Reliably construct backtraces when stack switching is enabled.

---

crates/cranelift/src/func_environ.rs
tests/misc_testsuite/typed-continuations/dup.wast

The specification allows duplicated occurrences of the same `tag` in filter list on the `resume` instruction (and `resume_throw` instruction). Only the first occurrence is relevant as it shadows the subsequent ones, however, cranelift complains if we emit duplicated case labels in a `Switch`, e.g.
```
$ ./target/debug/wasmtime wast -W=exceptions,function-references,typed-continuations dup.wast
thread '<unnamed>' panicked at 'Tried to set the same entry 0 twice', cranelift/frontend/src/switch.rs:58:9
```
This patch compiles only the first occurrence of a tag and skips subsequent entries.

Handle duplicated tag entries on `resume`.

---

Cargo.lock
crates/cranelift/Cargo.toml
crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/runtime/src/libcalls.rs
src/commands/compile.rs

This PR adds the facility to print from jitted code for debugging purposes.
This is done using the new macro `emit_debug_println!`, which is designed to be similar to Rust's `println!`.
Thus, analogously to writing 
```
println!("Hello {}, my favorite number is stored at {:p}, name, pointer)
```
we may now write
```
emit_debug_println!(env, builder, "Hello {}, my favorite number is stored at {:p}, name, pointer)
```
where `env` and `builder` are a `FuncEnvironment` and `FunctionBuilder`.
Note that using string literals with placeholders in them is not just to make the new printing functionality similar to the existing Rust macros, but there is also a technical reason: Using string literals means that we need not worry about allocation of string objects passed between generated code and …

Debug printing from generated code

---

Cargo.lock
cranelift/filetests/src/test_wasm/env.rs
cranelift/wasm/src/environ/dummy.rs
cranelift/wasm/src/environ/spec.rs
crates/cranelift/src/func_environ.rs
crates/environ/Cargo.toml
crates/environ/src/builtin.rs
crates/environ/src/vmoffsets.rs
crates/runtime/src/continuation.rs
crates/runtime/src/instance.rs
crates/runtime/src/libcalls.rs
tests/all/pooling_allocator.rs

Currently, the `VMContext` contains a pointer to a "payloads" object, which is used to store the values provided to a `suspend` invocation and makes them available in the handler. This object is opaque in the sense that we only manage it through libcalls, in particular using a libcall to extract a pointer to and underlying buffer with the actual data.
This PR changes that, instead putting a `wasmtime_continuations::Payloads` (basically a vector) object directly into the `VMContext`, which we then manipulate using generated code. We already have plenty of infrastructure for generating such code, as such `Payloads` objects are also used in `ContinuationObject`s.

Store Payloads object in VMContext and manage with generated code

---

crates/cranelift/src/func_environ.rs
crates/runtime/src/continuation.rs

Currently, we use `Payloads` objects for example to
- Propagate payloads from `suspend` calls to handlers
- From `resume` calls back to the `suspend` sites
In both cases, we proceed as follows:
1. Allocate a sufficiently sized data buffer within the `Payloads` object first
2. Write the payload data to it
3. Read the payload data on the receiving side
4. Deallocate the buffer within the `Payloads` object.
This PR changes this behavior: Instead of deallocating the buffer in step 4, we simply mark it as empty, but keep the buffer. Thus, we may change step 1 so that we first check if the `Payloads` object under consideration already has a sufficiently sized buffer. If so, we reuse it, and only need to allocate a new one otherwise.

Re-use Payloads object buffers

---

crates/continuations/src/lib.rs
crates/cranelift/src/func_environ.rs
crates/runtime/src/continuation.rs
crates/runtime/src/instance.rs

This PR refactors the `resume` libcall and its call sites (in generated code). The idea is that afterwards, the `resume` libcall should only be a slim wrapper around `wasmtime_fibre::Fiber::resume`. The only additional logic remaining in the libcall function is the encoding of the result as a u64. (ordinary return vs. suspend + tag information).
Thus, the following is moved out of the libcall, and now done by code generated in `translate_resume`:
1. Setting the active continuation within the `VMContext`.
2. Setting the `State` flags of the `ContinuationObject`.
Note that this PR is supposed to result in exactly the same actions being taken as before, just from generated code instead of the libcall.

Move operations from resume libcall to generated code

---

crates/fibre/src/unix/x86_64.rs

This PR adds some additional documentation to the `wasmtime_fibre_init` and `wasmtime_fibre_start` handwritten assembly functions. Due to how special these functions behave, the documentation shows the produced or expected stack layouts, as well as values of key registers.
Currently, these functions are identical to their counterparts in the original `fiber` crate. This documentation will become increasingly important as we optimise these functions further specificly for our needs and diverge from the original `fiber` crate.

Additional documentation of assembly functions in wasmtime-fibre

---

Cargo.lock

This patch brings our `Cargo.lock` in sync with the copy of upstream.
Resolves #69.

Synchronise with upstream's `Cargo.lock`.

---

crates/cranelift/src/func_environ.rs

This is a simpler alternative to #82 that does not implement a bespoke pattern matcher, but uses two calls to `str`'s `match_indices` function.

Revive emit_debug_print

---

crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

This patch makes the interfaces and implementations of continuation-related libcalls safer as they now handle traps/failures.
In addition, this patch increases the default fiber stack size to 2MB.

Safer continuations-related libcall implementations

---

crates/c-api/include/wasmtime/config.h
crates/c-api/src/config.rs

This patch adds options to enable the exception-handling, function references, and typed continuations proposals in C API.

C API option to enable the WasmFX instruction set

---

crates/continuations/src/lib.rs
crates/cranelift/src/func_environ.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/environ/src/builtin.rs
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

As of PR #98, each `ContinuationObject` contains an object of type `StackLimits`. In addition, there exists such an object for the main stack, it is stored in the `VMContext` and the `StackChain::MainStack` variant at the list of currently active continuations points to it. These `StackLimits` objects contain counterparts  of the stack-related fields in `VMRuntimeLimits`, namely `stack_limit` and the various `last_wasm_*` fields.
As of PR #98, the actual contents of these `StackLimits` are unused (and not updated). This changes in this PR:
While the `VMRuntimeLimits` continue to contain the stack-related information for the currently executing stack (either the main stack or a continuation), we ensure that for stacks that are *not* currently running, their corresponding `StackLimits` …

Backtrace support, part 2: Shadow VMRuntimeLimits for each stack

---

crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/environ/src/vmoffsets.rs
crates/runtime/src/continuation.rs
crates/runtime/src/instance.rs
crates/runtime/src/lib.rs
crates/wasmtime/src/runtime/store.rs
tests/all/pooling_allocator.rs
tests/all/typed_continuations.rs

There is a currently a conceptual error in the implementation, where the chain of active stacks (= continuations + the main stack) is stored per `Instance`/`VMContext`. 
This means that when a function `$f` calls an imported function `$g`, where `$f` and `$g` are not part of the same instance, their stack chains are completely separate. For example, it is not possible to `suspend` to a tag `$t` in `$g` and handle this in a resume block in `$f` (assuming that the underlying modules import and export the tag `$t` so that it is shared between the two).
This PR rectifies this situation by sharing a single `StackChain` object between all instances of the same `Store`. The `VMContext` then contains merely a pointer to this shared chain, rather than a chain of its own. This fully mirrors how the …

Support for inter-instance stack switching

---

cranelift/wasm/src/code_translator.rs
crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/environ/src/builtin.rs
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs

Currentlly, `wasmtime_continuations::Payloads` looks like this (after inlining some definitions):
```rust
pub struct Payloads {
pub length: usize,
pub capacity: usize,
pub data: *mut u128,
}
```
This PR changes the type of the `capacity` and `length` fields from `usize` to `u32`. This is reasonable, as the maximum length/capacity values we will see are bounded by the maximum of the following:
- Number of parameters/return values of any function used as a continuation
- Number of parameters/return values of any tag
Of course, it would be nice to somehow enforce the actual maximum of these values that we support, but that seems out of scope for this PR.
Each `ContinuationObject` contains two such `Payloads` objects, so this change saves us 16 bytes per continuation. This is probably not a …

Store length and capacity of Payloads object as u32

---

crates/cranelift/src/func_environ.rs

This commit adds a comment to `crates/cranelift/src/func_environ.rs` to document that the hack in `before_translate_function` is the culprit of the disas expect test diversion.

Document the culprit of disas expect tests diversion

---

crates/cli-flags/src/lib.rs
crates/continuations/src/lib.rs
crates/runtime/src/continuation.rs
crates/runtime/src/traphandlers/backtrace.rs
crates/wasmtime/src/config.rs
tests/all/typed_continuations.rs

Currently, we can overflow the stack while running inside a continuation, without the runtime having any way of detecting this.
This PR partially rectifies this, by making the existing stack limit checks that get emitted by cranelift in every wasm function prelude work correctly while running inside a continuation.
All that was required to enable the stack limit checks was the following:
1. Stop zero-ing out the `stack_limit` value in `VMRuntimeLimits` whenever we `resume` a continuation. 
2. When creating a continuation, set a reasonable value for the `stack_limits` value in its `StackLimits` object.
Note that all the required infrastructure to make sure that whenever we switch stacks, we save and restore the `stack_limits` value inside `VMRuntimeLimits` and the `StackLimits` object of …

Enable limited stack overflow checks while running inside continuations

---

crates/runtime/src/fibre/unix.rs
crates/runtime/src/fibre/unix/x86_64.rs

Currently, external tools that want to inspect our stack while running wasmfx code,  such as `gdb`, `lldb` and `perf`, need to rely on the DWARF information that wasmtime produces. In particular, we have some hand-crafted DWARF directives in  `crates/runtime/src/fibre/unix/x86_64.rs` that encode the parent-child relationship between continuations' stacks.
Unfortunately, `perf` gets stuck when working on information recorded with `perf record --call-graph dwarf`, meaning that it is having issues with the DWARF-based backtrace frame information that wasmtime offers.
Luckily, in generated code, wasmtime/cranelift use frame pointers to facilitate stack walking. However, these frame pointer chains are currently broken when crossing continuation stacks: Inside `wasmtime_fibre_start`, the …

Enable backtrace creation purely based on frame pointer walking

---

crates/cranelift/src/wasmfx/baseline.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/cranelift/src/wasmfx/shared.rs

This patch refactors the libcall code generation to remove the redundancy introduced by #140.

Refactor libcall code generation in WasmFX modules.

---

Cargo.toml
cranelift/wasm/src/code_translator.rs
cranelift/wasm/src/environ/spec.rs
crates/continuations/src/lib.rs
crates/cranelift/src/func_environ.rs
crates/cranelift/src/wasmfx/baseline.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/cranelift/src/wasmfx/shared.rs
crates/environ/src/builtin.rs
crates/runtime/src/continuation.rs
crates/runtime/src/libcalls.rs
crates/wasmtime/src/runtime/trampoline/global.rs
crates/wasmtime/src/runtime/types.rs
crates/wasmtime/src/runtime/types/matching.rs
tests/misc_testsuite/typed-continuations/cont_bind4.wast

This PR renames `ContinuationObject` to `VMContRef` and `ContinuationReference` to `VMContObj`.
This was mostly just a search-replace job, but also involved renaming lots of variables named things like `contref` or `contobj` (and various variations thereof), as well as replacing mentions of "continuation object" in text.
The baseline implementation remains mostly unchanged since it was already using that nomenclature, only some minor changes at the boundaries/when interacting with functions defined in both implementations (e.g., `typed_continuations_load_continuation_reference`) were necessary.
This resolves #104.

Rename ContinuationObject and ContinuationReference

---

crates/runtime/src/continuation.rs
crates/runtime/src/fibre/mod.rs
crates/runtime/src/fibre/unix.rs
crates/runtime/src/fibre/unix/x86_64.rs

Currently, we inherit the following behavior from the `wasmtime_fiber` crate:
The toplevel function executed inside a `Fiber` is a Rust closure. However, this flexibility is not required for our use case: The function we want to run inside a continuation is always the array call trampoline of a wasm function.
This PR specializes our module `wasmtime_runtime::fibre` to our particular use case, getting rid of the involved closures. Instead, all the required data is passed around explicitly in function arguments, instead of being implicitly stored in a closure. This has the following advantages:
1. We do not need to allocate a `Box` holding the closure anymore.
2. The function `wasmtime_runtime::fibre::unix::fiber_start`, which is the Rust entry point for execution inside a Fiber, is no …

Initiate execution of continuations without use of closures

---

crates/cranelift/src/wasmfx/shared.rs

This patch tweaks the `call_builtin` macro ever-so-slightly by making sure it is hygienic (i.e. generated names doesn't clash with those in the current scope) by enclosing generated names in local scopes.

Hygienic `call_builtin` macro.

---

Cargo.lock
Cargo.toml
crates/cranelift/src/func_environ.rs

One of the previous merges inadvertently dropped support for certain
operations on continuation tables. This patch is a quick fix to
restore the functionality by interpreting continuation tables as func
tables.
Also, this PR imports the wasmfx-tools patch for subtyping check on `cont.new`.

Restore continuation table functionality

---

crates/c-api/include/wasmtime/linker.h
crates/c-api/src/linker.rs

The C API for using the wasmtime linker currently only gives access to the `allow_shadowing` setting of the linker, but not to the `allow_unknown_exports` setting. However, the latter setting needs to be enabled in order to allow exporting the global `__stack_pointer`. This is what's causing the issue described in wasmfx/waeio#2.
(Alternatively, we may add `__stack_pointer` to the list of blessed globals in the `command` function in crates/wasmtime/src/runtime/linker.rs, but the comments there suggest that new items shouldn't be added to that list. Therefore, just making this setting accessible in the C API seems less controversial.)

Add wasmtime_linker_allow_unknown_exports to C API

---

cranelift/codegen/src/ir/memflags.rs
cranelift/codegen/src/ir/trapcode.rs
crates/continuations/src/lib.rs
crates/cranelift-shared/src/lib.rs
crates/cranelift/src/lib.rs
crates/cranelift/src/wasmfx/baseline.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/cranelift/src/wasmfx/shared.rs
crates/environ/src/builtin.rs
crates/environ/src/trap_encoding.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/libcalls.rs
tests/all/typed_continuations.rs

This patch makes continuation objects allocation free by representing a continuation object as an immediate, whose 16 high bits are the witness of the continuation reference revision counter, and the 48 low bits are the actual continuation reference address. This gives us a cheap way of implementing the linearity check for continuations. Using 16 bits for the witness, means that we are currently restricted to 2^16 uses, which suffices for our examples and benchmarks, but isn't sufficient in general. However, we can readily generalise this implementation in a subsequent patch.
The compile time option `unsafe_disable_continuation_linearity_check` preserves its behaviour.
Resolves #178.

Continuation objects as fat pointers

---

.github/workflows/main.yml
crates/continuations/src/lib.rs
crates/cranelift/src/func_environ.rs
crates/environ/src/builtin.rs
crates/wasmtime/src/runtime/externals/table.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/libcalls.rs
crates/wasmtime/src/runtime/vm/table.rs

This patch removes the "interpret continuation tables as function references tables" hack in favour of a dedicated handling of continuation tables. 
Note this patch does not implement the embedder-side of things.
Resolves #133.

Bespoke continuation table type

---

README.md
examples/generator.wat

This PR adds some documentation at the beginning of README.md, with the original Wasmtime documentation left below.
The README contains a minimal generator example to facilitate just copy-pasting it elsewhere and playing with it. The full version of the example, where printing is actually implemented, is put in `examples/generator.wat`.

WasmFX-specific documentation in README.md

---

.github/workflows/main.yml
crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/fibre/mod.rs
crates/wasmtime/src/runtime/vm/fibre/unix.rs
crates/wasmtime/src/runtime/vm/traphandlers/backtrace.rs

This PR performs a refactoring required by a follow-up PR that will implement actual pooling of `VMContRef`s.
This PR removes the types `Fiber` and `Suspend` from the `fibre` create (i.e., our version of `wasmtime-fiber`). These two types are effectively leftovers from `wasmtime-fiber`, but only add a layer of unnecessary indirection at this point.
Note that the `fibre::FiberStack` type remains. Some functions originally implemented on `Fiber` are moved to `FiberStack` now. Further, the `VMContRef` definition used in the optimized implementation now owns a `fibre::FiberStack` directly, rather than storing a `Fiber` as a wrapper around the `FiberStack`.
This PR does not affect the baseline implementation since it doesn't use the `fibre` crate at all.

Remove fibre::{Fiber, Suspend} types

---

.github/workflows/benchfx.yml

This PR adds a new Github Actions workflow that runs our benchfx benchmarks on the PR and compares performance against the PR base (in most cases: `main`).
The necessary setup and actual running of benchmarks is performed using the benchfx `harness.py`.
The only minor complication is that I'm using the cache feature of Github Actions to speed up building things. Everything related to caching is extensively documented in the workflow file.
Currently, the workflow is set up so that any regression by more than 7% causes the job to fail. I've found the Github workers to be surprisingly stable (almost all of my test runs had performance differences of +-1 % when comparing the same Wasmtime commit against each other), but there was a single case when the difference was 5% due to noise.
This …

CI job for performance regression testing

---

.github/workflows/main.yml
crates/continuations/src/lib.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/fibre/mod.rs
crates/wasmtime/src/runtime/vm/fibre/unix.rs
crates/wasmtime/src/runtime/vm/instance.rs
crates/wasmtime/src/runtime/vm/instance/allocator/wasmfx_allocator.rs

This PR extends the existing `WasmFXAllocator` to also allocate `VMContRefs` in addition to `FiberStacks`. In particular, this means the *pooling* implementation of the allocator now pools these `VMContRef` objects, too.
The overall goal is that eventually, when the pooling allocator is enabled, executing `cont.new` instructions can usually be done without needing to use the system allocator.
To this end, our pooling allocator is equipped with a `Vec<VMContRef>`. The underlying mechanism for maintaining which indices into the pool are free vs used (provided by `SimpleIndexAllocator`) remains unchanged: The idea is that index `i` in the pool refers to the i-th VMContRef (in the `Vec`) and the i-th region of stack memory (from the overall `mmap`-ped stack memory allocation).
One notable …

VMContRef pooling

---

cranelift/codegen/meta/src/shared/instructions.rs
cranelift/codegen/src/isa/x64/inst.isle
cranelift/codegen/src/isa/x64/inst/emit.rs
cranelift/codegen/src/isa/x64/inst/mod.rs
cranelift/codegen/src/isa/x64/lower.isle
cranelift/codegen/src/isa/x64/pcc.rs
cranelift/interpreter/src/step.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/environ/src/builtin.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/libcalls.rs

This PR is part of a series that implements native stack switching.
This particular PR moves one particular aspect out of the `tc_resume` libcall: Updating the `StackLimits` object of the parent of the continuation being resumed.
Doing this *inside* the libcall had practical reasons: We needed access to the updated `last_wasm_exit_pc`/`last_wasm_exit_fp`   value in the `VMRuntimeLimits` in order to copy them into the `StackLimits`. However, these values are only updated by the libcall mechanism itself, so they are only available inside the libcall implementation itself.
This PR obtains the corresponding values using code generated for `resume`, before the actual `tc_resume` libcall happening, and writes them into the `StackLimits`.
1. We use the `get_frame_pointer` instruction to obtain a …

In resume instruction, update StackLimits from generated code

---

crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/wasmtime/src/runtime/store.rs
crates/wasmtime/src/runtime/vm/continuation.rs

This PR is part of an effort to implement more efficient effect forwarding.
This particular PR makes our tracking of the state of continuations more fine-grained.
Currently, the `State` enum only allows us to distinguish three cases:
1. A continuation was allocated, but never invoked (`State::Allocated`).
2. A continuation has been invoked at some point, and not returned, yet (`State::Invoked`).
3. A continuation has returned  (`State::Returned`).
This PR replaces `State::Invoked` with three new states, indicating more closely what's going on:
-  `State::Running` indicates that the continuation is the one currently executing code
- `State::Parent` indicates that a continuation is suspended because it `resumed` another one.
- `State::Suspended` indicates that a continuation was suspended …

More fine-grained tracking of continuations' states

---

.github/workflows/benchfx.yml

This patch disables the CI benchmark job. We should reactivate it after our toolchains have been brought up to date with the new binary format.

[CI] Disable benchmark job

---

crates/c-api/include/wasmtime/config.h
crates/environ/src/builtin.rs
crates/wasmtime/src/config.rs

This patch rebrands a few public APIs from typed-continuations to stack-switching.
Resolves #146.

Rebranding

---

tests/misc_testsuite/stack-switching/linking_tags1.wast
tests/misc_testsuite/stack-switching/linking_tags2.wast

This PR splits `linking_tags.wast` into two files.
This is a preparation step needed to land fast effect forwarding due to the following:
`linking_tags.wast` currently has two `assert_suspension` directives. In the current implementation, we are always on the main stack when we detect that a tag is unhandled and trap from there. However, in the presence of fast effect forwarding, we detect the lack of an appropriate handler at the `suspend` site and trap there (i.e., possibly while still running on a continuation stack).
As a result, the `assert_suspension` directives in `linking_tags.wast` trigger the problem described in #253 as soon as fast fowarding lands. As a workaround, this PR splits the file into two, where the `assert_suspension` is the very last step in each test (i.e., we …

Split linking_tags.wast into two files

---

crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/wasmtime/src/runtime/vm/continuation.rs

Currently,  `VMContRef` objects in the optimized implementation have two fields of type `Payloads`:
- `args`, where the arguments and return values stored by the toplevel function running inside the continuation are stored (used by the array call trampoline)
- `tag_return_values`, which is used to store payloads of suspended continuations provided by `resume` or `cont.bind` (thus, their types must correspond to the return type of the tag that we suspended with)
This PR renames the second field, in order to prepare for `switch`: In the presence of `switch`, the name `tag_return_values` does not make sense anymore: We will be storing `switch` arguments in that vector as well.
I've chosen `values` as the new name, inspired by how the baseline implementation calls its counterpart of that …

Rename tag_return_values field and payload-related helper functions

---

cranelift/codegen/meta/src/shared/instructions.rs
cranelift/codegen/src/isa/x64/inst.isle
cranelift/codegen/src/isa/x64/inst/emit.rs
cranelift/codegen/src/isa/x64/inst/mod.rs
cranelift/codegen/src/isa/x64/lower.isle
cranelift/codegen/src/isa/x64/pcc.rs
cranelift/interpreter/src/step.rs
crates/continuations/src/lib.rs
crates/cranelift/src/wasmfx/optimized.rs
crates/wasmtime/src/runtime/vm/continuation.rs
crates/wasmtime/src/runtime/vm/fibre/mod.rs
crates/wasmtime/src/runtime/vm/fibre/unix.rs
crates/wasmtime/src/runtime/vm/traphandlers/backtrace.rs

When creating a backtrace while running some continuation `c` with parent `p` (another continuation or the main stack), the following happens at the moment:
After traversing the stack frames of `c`, we need to traverse the stack frames of `p`. To this end, we look at the `StackLimits` object of `p`.
The `last_wasm_exit_{fp, pc}` fields therein tell us the frame pointer and program counter at the point where we stopped execution in `p`. This must have been at a `resume` Wasm instruction that resumed `c`. This FP and PC allows us to travese the stack frames of `p`.
Note that the fields in `StackLimits` are updated by the various stack switching instructions. The `last_wasm_exit_{fp,pc}` fields are only ever used for creating backtraces, they do not influence control flow at all.
Since #223, …

Make backtrace creation more accurate to support GC
